CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE PERSONAL_INFO (
STUDENT_PRN VARCHAR(10) UNIQUE,
NAME_STD VARCHAR(100),
EMAIL VARCHAR(254) UNIQUE NOT NULL,
PRIMARY KEY(STUDENT_PRN)
);
SELECT*FROM PERSONAL_INFO;
CREATE TABLE Attendance_Logs (
    LOG_ID INT AUTO_INCREMENT, -- Automatically counts 1, 2, 3...
    STUDENT_PRN VARCHAR(20),
    SCAN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Automatically records the time
    PRIMARY KEY (LOG_ID),
    FOREIGN KEY (STUDENT_PRN) REFERENCES PERSONAL_INFO(STUDENT_PRN)
);
SELECT*FROM Attendance_Logs;
ALTER TABLE students ADD COLUMN face_descriptor TEXT;
